query getAnime($id:ID){
  anime(_id:$id){
    id
    episodes
    duration
    format
    source
    status
    season
    description
    synonyms
    titles{
      romaji
      english
      native
    }
    images{
      cover
      banner
    }
    startDate{
      startDay
      startMonth
      startYear
    }
    endDate{
      endDay
      endMonth
      endYear
    }
    episodeLists{
      _id  
      title
      thumbnail
      episode
    }
  }
}