query getEpisode($id:ID){
  episodeSearch(_id:$id){
    _id
    episodeLists{
      ismkv
      stream
      thumbnail
      title
      episode
      length
      dualAudio
      subsBy
      BDrip
      resolution
      codec
      aspectRatio
      frameRate
      audioTerm
    }
  }
}